import { useNavigate, Link } from "react-router-dom";
import { Sparkles, Clock, Lock, History } from "lucide-react";
import PageLayout from "../../layouts/PageLayout";
import uterusImg from "../../assets/uterus.png";

const features = [
  {
    icon: Sparkles,
    title: "AI-Powered Assessment",
    desc: "Our model analyzes your symptoms and lifestyle data.",
  },
  {
    icon: Clock,
    title: "Quick & Easy",
    desc: "Takes only 5-7 minutes to complete.",
  },
  {
    icon: Lock,
    title: "100% Confidential",
    desc: "Your data is private and secure with us.",
  },
];

export default function PCOSIntro() {
  const navigate = useNavigate();

  return (
    <PageLayout
      title="PCOS Assessment"
      subtitle="Understand your symptoms better with AI."
    >
      <div className="mx-auto max-w-md">
        <div className="rounded-2xl bg-white p-6 shadow-[0_4px_14px_rgba(0,0,0,0.04)] ring-1 ring-black/5">
          
          {/* Uterus Image */}
          <div className="relative mx-auto flex h-40 w-40 items-center justify-center">
            <div className="absolute inset-0 rounded-full bg-[#FEE4EB]" />

            <img
              src={uterusImg}
              alt="Uterus illustration"
              className="relative h-28 w-28 object-contain mix-blend-multiply"
            />
          </div>

          <div className="mt-5 space-y-4 border-t border-[#F7DCE4] pt-5">
            <h2 className="font-display text-base font-semibold text-[#0D0D0D]">
              What is PCOS?
            </h2>

            <p className="text-sm leading-relaxed text-[#8F8C8C]">
              Polycystic Ovary Syndrome (PCOS) is a hormonal condition that
              affects women of reproductive age and can impact menstrual
              cycles, hormone levels and overall health.
            </p>

            <div className="space-y-3 pt-1">
              {features.map(({ icon: Icon, title, desc }) => (
                <div key={title} className="flex items-start gap-3">
                  <span className="flex h-9 w-9 flex-shrink-0 items-center justify-center rounded-xl bg-[#FEE4EB] text-[#F33B7D]">
                    <Icon className="h-4 w-4" />
                  </span>

                  <div>
                    <p className="text-sm font-semibold text-[#0D0D0D]">
                      {title}
                    </p>

                    <p className="text-xs text-[#8F8C8C]">
                      {desc}
                    </p>
                  </div>
                </div>
              ))}
            </div>

            <div className="rounded-xl bg-[#FEE4EB] p-3">
              <p className="text-xs leading-relaxed text-[#3D3939]">
                <span className="font-semibold text-[#F33B7D]">
                  Disclaimer:
                </span>{" "}
                This assessment is generated by an AI model and is intended
                for informational purposes only. It is not a medical
                diagnosis. Please consult a qualified healthcare professional
                for confirmation and treatment.
              </p>
            </div>
          </div>
        </div>

        <button
          onClick={() => navigate("/pcos-detection/assessment")}
          className="mt-4 w-full rounded-full bg-[#F33B7D] px-6 py-3 text-sm font-semibold text-white shadow-[0_14px_28px_-6px_rgba(243,59,125,0.5)] transition hover:-translate-y-0.5"
        >
          Start Assessment
        </button>

        <Link
          to="/pcos-detection/history"
          className="mt-3 flex w-full items-center justify-center gap-2 rounded-full bg-[#F33B7D] px-6 py-3 text-sm font-semibold text-white shadow-[0_14px_28px_-6px_rgba(243,59,125,0.5)] transition hover:-translate-y-0.5"
        >
          <History className="h-4 w-4" />
          View Assessment History
        </Link>
      </div>
    </PageLayout>
  );
}