const PCOSAssessment = require("../models/PCOSAssessment");
const ApiError = require("../utils/ApiError");
const { predictPCOS } = require("./ai.service");
const getRecommendations = require("../utils/pcosRecommendations");

// =========================================
// Create Assessment
// =========================================

const createAssessment = async (userId, answers) => {

  const result = await predictPCOS(answers);
  const recommendations = getRecommendations(
  result,
  answers
);

  const assessment = await PCOSAssessment.create({

  user: userId,

  answers,

  probability: result.probability,

  risk: result.risk,

  prediction: result.prediction,

  confidence: result.confidence,

  topFactors: result.topFactors,

  recommendations,

  disclaimer:
    "This assessment is generated by an AI model and is intended for informational purposes only. It is not a medical diagnosis. Please consult a qualified healthcare professional for confirmation and treatment.",

});

  return assessment;

};

// =========================================
// Latest Assessment
// =========================================

const getLatestAssessment = async (userId) => {

  const assessment = await PCOSAssessment.findOne({
    user: userId,
  })
    .sort({ createdAt: -1 });

  if (!assessment) {
    throw new ApiError(
      404,
      "No PCOS assessment found."
    );
  }

  return assessment;

};

// =========================================
// Assessment History
// =========================================

const getAssessmentHistory = async (userId) => {

  const history = await PCOSAssessment.find({
    user: userId,
  })
    .sort({ createdAt: -1 });

  return history;

};

// =========================================
// Dashboard
// =========================================

const getDashboard = async (userId) => {

  const assessment = await PCOSAssessment.findOne({
    user: userId,
  }).sort({ createdAt: -1 });

  if (!assessment) {
    throw new ApiError(
      404,
      "No PCOS assessment found."
    );
  }

  return {
    score: assessment.probability,

    risk: assessment.risk,

    prediction: assessment.prediction,

    confidence: assessment.confidence,

    recommendations: assessment.recommendations,

    topFactors: assessment.topFactors,

    lastAssessment: assessment.createdAt,
  };

};

// =========================================
// Delete Assessment
// =========================================

const deleteAssessment = async (userId, assessmentId) => {

  const assessment = await PCOSAssessment.findOne({
    _id: assessmentId,
    user: userId,
  });

  if (!assessment) {
    throw new ApiError(
      404,
      "Assessment not found."
    );
  }

  await assessment.deleteOne();

  return true;

};

module.exports = {
  createAssessment,
  getLatestAssessment,
  getAssessmentHistory,
  getDashboard,
  deleteAssessment,
};